# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('tamanho', models.IntegerField(blank=True, choices=[(1, '10x10'), (2, '30x30'), (3, '70x70')], default=1)),
            ],
        ),
    ]
