# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('minimo_permitido', models.IntegerField(blank=True, verbose_name='Minimo de unidades permitidas para compra')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('aberto', models.BooleanField(default=False, verbose_name='Aberto')),
            ],
        ),
        migrations.AddField(
            model_name='preco',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
    ]
