# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preco',
            name='minimo_permitido',
        ),
        migrations.AddField(
            model_name='produto',
            name='minimo_permitido',
            field=models.IntegerField(blank=True, default=3, verbose_name='Minimo de unidades permitidas para compra'),
        ),
    ]
