# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='tamanho',
            field=models.IntegerField(blank=True, choices=[(1, '10x10'), (2, '30x30'), (3, '70x70')], default=1, null=True),
        ),
    ]
