# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170329_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='aberto',
            field=models.BooleanField(default=False, verbose_name='Aberto'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='tipos',
            field=models.IntegerField(blank=True, choices=[(1, 'A/M'), (2, 'C/M'), (3, 'F/M')], default=2, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='ttamanho',
            field=models.BooleanField(default=False, verbose_name='Tem atributos de tamanho?'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='ttipo',
            field=models.BooleanField(default=False, verbose_name='Tem tipos?'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tamanho',
            field=models.IntegerField(blank=True, choices=[(1, '10x10'), (2, '30x30'), (3, '70x70')], default=1, null=True, verbose_name='Tamanho'),
        ),
    ]
