# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produto_maximo_permitido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('imagem', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
